version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: cop_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=cop_db

  backend:
    build: ./backend
    container_name: cop_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - DATABASE_NAME=cop_db
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: cop_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  mongodb_data:
